model_ema: True
criterion: MSELoss
optimizer: 
  name: adam # adamw, adam, sgd
  lr: 3e-4
  weight_decay: 0
  momentum: 0.9
  clipping: False
scheduler:
  name: CosineAnnealingLR
  min_lr: 1e-7
  # name: ReduceLROnPlateau
  # lr_factor: 0.5
  # patience: 5
  warmup: False
