model_ema: False
criterion: MSELoss
loss_alpha: 100
optimizer: 
  name: adam # adamw, adam, sgd
  lr: 3e-4
  amsgrad: True # for adam
  weight_decay: 0
  momentum: 0.9 # for sgd
  clipping: False
scheduler:
  # name: CosineAnnealingLR
  # min_lr: 1e-7
  #
  name: ReduceLROnPlateau
  lr_factor: 0.4
  patience: 2
  threshold_mode: 'rel'
  cooldown: 0
  min_lr: 1e-7
  eps: 1e-08
  #
  warmup: False