base: '/shared/youngkim/dacon-sem'
data: '/shared/Samsung'
submissions: '/shared/youngkim/dacon-sem/submissions/'
weights: '/shared/youngkim/dacon-sem/weights/'
pretrained: '/shared/youngkim/dacon-sem/weights/baseline_aux-29:11:33:42/14_last.pth'