base: '/shared/youngkim/dacon-sem'
data: '/shared/Samsung'
submissions: '/shared/youngkim/dacon-sem/submissions/'
weights: '/shared/youngkim/dacon-sem/weights/'
pretrained: '/shared/youngkim/dacon-sem/weights/original-07:02:58:03/10.pth'