base: '/shared/youngkim/dacon-sem'
data: '/shared/Samsung'
submissions: '/shared/youngkim/dacon-sem/submissions/'
weights: '/shared/youngkim/dacon-sem/weights/'
pretrained: '/shared/youngkim/dacon-sem/weights/baseline-29:06:22:28/9.pth'