base: '/shared/youngkim/dacon-sem'
data: '/shared/Samsung'
submissions: '/shared/youngkim/dacon-sem/submissions/'
weights: '/shared/youngkim/dacon-sem/weights/'
pretrained: '/shared/youngkim/dacon-sem/weights/baseline_aux_alpha100-29:11:58:51/7.pth'