_target_: src.models.unet.get_smp_model

# params of model class __init__ function
encoder_name : "efficientnet-b0"  # choose encoder, e.g. mobilenet_v2 or efficientnet-b7
in_channels : 1                   # model input channels (1 for gray-scale images, 3 for RGB, etc.)
classes : 1                       # model output channels (number of classes in your dataset)
activation : 'sigmoid'