# @package _global_

defaults:
  - _self_
  - datamodule: sem.yaml
  - model: basic.yaml
  - path: cricket.yaml
  - trainer: default.yaml

name: 'first_try'
device: 'cuda:0'
seed: 42

DEBUG: True
small_dataset: False

# learning
resume: False
epoch: 30
es_patience: 5 # if es_patient == 0, do not early stop.
mixed_precision: True

# etc
original_img_size: [72, 48]

# set in run codes
dt_string: None
len_train_loader: None