# @package _global_

defaults:
  - _self_
  - datamodule: sem.yaml
  - model: unet.yaml
  - path: cricket.yaml
  - trainer: default.yaml

name: 'baseline_unet++_eff_b0'
device: 'cuda:0'
seed: 42

DEBUG: False
small_dataset: False

# learning
resume: False
epoch: 15
es_patience: 0 # if es_patient == 0, do not early stop.
mixed_precision: False

# etc
original_img_size: [72, 48]

# set in run codes
dt_string: None
len_train_loader: None

# wandb
project: 'dacon-sem'
entity: 'normalkim'