_target_: src.datasets.sem_datamodule.SEMDataModule

# params of datamodule class __init__ function
data_path: ${path.data} # data_path is specified in config.yaml
n_splits: 5
fold: 0
batch_size: 128
num_workers: 8
pin_memory: True
verbose: True
resize: [96, 64]